const ABSTRACT = { chainId: '0xab5', chainName: 'Abstract', rpcUrl: 'https://api.mainnet.abs.xyz', explorer: 'https://abscan.org' };
const statList = document.querySelector('#statList');
const badgeGrid = document.querySelector('#badgeGrid');
const activityList = document.querySelector('#activityList');
const toast = document.querySelector('#toast');
const status = document.querySelector('#connectionStatus');
let toastTimer; let activeAddress = null;
const short = address => `${address.slice(0, 6)}...${address.slice(-4)}`;
const hexToNumber = value => Number.parseInt(value || '0x0', 16);
const eth = wei => Number(BigInt(wei || '0x0')) / 1e18;
function showToast(message){toast.textContent=message;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),3000)}
function setStatus(message,kind=''){status.textContent=message;status.className=`connection-status ${kind}`}
async function rpc(method,params=[]){const response=await fetch(ABSTRACT.rpcUrl,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:Date.now(),method,params})});if(!response.ok)throw new Error(`Abstract RPC returned ${response.status}`);const payload=await response.json();if(payload.error)throw new Error(payload.error.message||'Abstract RPC error');return payload.result}
async function ensureAbstract(provider){const current=await provider.request({method:'eth_chainId'});if(current.toLowerCase()===ABSTRACT.chainId)return;try{await provider.request({method:'wallet_switchEthereumChain',params:[{chainId:ABSTRACT.chainId}]})}catch(error){if(error.code!==4902)throw error;await provider.request({method:'wallet_addEthereumChain',params:[{chainId:ABSTRACT.chainId,chainName:ABSTRACT.chainName,nativeCurrency:{name:'Ether',symbol:'ETH',decimals:18},rpcUrls:[ABSTRACT.rpcUrl],blockExplorerUrls:[ABSTRACT.explorer]}]})}}
function renderStats(stats){statList.innerHTML=stats.map(([name,value,display])=>`<div class="stat-row"><span class="stat-name">${name}</span><span class="bar"><i style="width:${value}%"></i></span><span class="stat-value">${display}</span></div>`).join('')}
function badgeSet({txCount,balance,isContract}){const badges=[];if(txCount>0)badges.push({icon:'✦',title:'First Signal',desc:'This wallet has made its first move on Abstract.',meta:'VERIFIED · LIVE',color:'#d7ff5f'});if(txCount>=10)badges.push({icon:'↗',title:'Active Walker',desc:`${txCount.toLocaleString()} transactions signed on mainnet.`,meta:'VERIFIED · LIVE',color:'#9f7bff'});if(txCount>=50)badges.push({icon:'☄',title:'Deep Explorer',desc:'You kept going after the first few transactions.',meta:'VERIFIED · LIVE',color:'#ff855e'});if(balance>0)badges.push({icon:'◈',title:'Funded',desc:`${balance.toFixed(4)} ETH currently visible on Abstract.`,meta:'VERIFIED · LIVE',color:'#65d9d2'});if(isContract)badges.push({icon:'⌂',title:'Smart Account',desc:'This address has deployed code on Abstract.',meta:'VERIFIED · LIVE',color:'#cba8ff'});if(txCount===0&&balance===0)badges.push({icon:'◌',title:'Blank Canvas',desc:'No activity or balance yet. Every identity starts here.',meta:'VERIFIED · LIVE',color:'#8f8c87'});return badges}
function renderBadges(badges){document.querySelector('#badgeCount').textContent=badges.length;badgeGrid.innerHTML=badges.map(b=>`<article class="badge" style="--badge-color:${b.color}"><div class="badge-icon" style="color:${b.color}">${b.icon}</div><div class="badge-title">${b.title}</div><div class="badge-desc">${b.desc}</div><div class="badge-meta">${b.meta}</div></article>`).join('')}
function renderFacts({txCount,balance,isContract,blockNumber}){activityList.innerHTML=[['✦','Transaction count',`${txCount.toLocaleString()} signed on Abstract`,'RPC'],['◈','ETH balance',`${balance.toFixed(5)} ETH`,'RPC'],['⌂','Account type',isContract?'Smart contract account':'Externally owned account','RPC'],['◎','Network head',`Block ${blockNumber.toLocaleString()}`,'LIVE']].map(([icon,label,value,time])=>`<div class="activity-item"><div class="activity-icon">${icon}</div><div class="activity-text">${label} <span>· ${value}</span></div><div class="activity-time">${time}</div></div>`).join('')}
async function loadProfile(address,connected=false){activeAddress=address;setStatus('Reading live data from Abstract mainnet…');document.querySelector('#dashboard').classList.remove('hidden');document.querySelector('#walletAddress').textContent=short(address);document.querySelector('#explorerLink').href=`${ABSTRACT.explorer}/address/${address}`;document.querySelector('#walletTitle').textContent=connected?'Your proof, decoded.':'Public proof, decoded.';document.querySelector('#dashboard').scrollIntoView({behavior:'smooth'});try{const [balanceHex,nonceHex,code,blockHex]=await Promise.all([rpc('eth_getBalance',[address,'latest']),rpc('eth_getTransactionCount',[address,'latest']),rpc('eth_getCode',[address,'latest']),rpc('eth_blockNumber')]);const balance=eth(balanceHex);const txCount=hexToNumber(nonceHex);const blockNumber=hexToNumber(blockHex);const isContract=code&&code!=='0x';const activity=Math.min(100,txCount);const funding=Math.min(100,balance>0?Math.max(18,Math.round(Math.log10(balance+1)*100)):0);const account=isContract?100:42;const proof=Math.min(10,Math.max(0,((activity+funding+account)/30)).toFixed(1));document.querySelector('#score').textContent=proof;document.querySelector('#identity-type').textContent=isContract?'SMART ACCOUNT · ABSTRACT MAINNET':'EOA · ABSTRACT MAINNET';renderStats([['ACTIVITY',activity,txCount.toLocaleString()],['FUNDING',funding,`${balance.toFixed(3)} ETH`],['ACCOUNT',account,isContract?'CODE':'EOA'],['NONCE',Math.min(100,txCount),txCount.toLocaleString()],['CHAIN',100,'2741'],['FRESHNESS',100,`#${blockNumber.toLocaleString()}`]]);renderBadges(badgeSet({txCount,balance,isContract}));renderFacts({txCount,balance,isContract,blockNumber});setStatus('Live proof generated from Abstract mainnet.','success');document.querySelector('#scanBtn').innerHTML='Refresh proof <span>↻</span>';showToast('Live Abstract proof generated')}catch(error){setStatus(`Could not read Abstract mainnet: ${error.message}`,'error');showToast('Abstract RPC could not be reached')}}
async function connectAndScan(){if(!window.ethereum){setStatus('No browser wallet detected. Use the public profile loader below or install a wallet extension.','error');document.querySelector('#walletFallback')?.classList.add('visible');showToast('Wallet extension not found');return}try{setStatus('Waiting for wallet approval…');await ensureAbstract(window.ethereum);const accounts=await window.ethereum.request({method:'eth_requestAccounts'});if(!accounts?.[0])throw new Error('No account selected');document.querySelector('#walletFallback')?.classList.remove('visible');await loadProfile(accounts[0],true)}catch(error){setStatus(error.message||'Wallet connection cancelled.','error');showToast('Wallet connection cancelled')}}
function publicShareUrl(){const url=new URL(window.location.href);if(activeAddress)url.searchParams.set('address',activeAddress);return url.toString()}
async function shareProfile(){const url=publicShareUrl();try{await navigator.clipboard.writeText(url);showToast('Live profile link copied')}catch{showToast('Live profile link ready')}}
function shareOnX(){const url=publicShareUrl();const text=activeAddress?`My onchain personality on Abstract: ${short(activeAddress)}\n\nDiscover your proof with Proofly ✦`:'Discover your onchain personality with Proofly ✦';window.open(`https://x.com/intent/post?text=${encodeURIComponent(text)}&url=${encodeURIComponent(url)}&hashtags=Proofly,Abstract`,'_blank','noopener,noreferrer')}
document.querySelector('#scanBtn').addEventListener('click',connectAndScan);document.querySelector('#connectBtn').addEventListener('click',connectAndScan);document.querySelector('#shareBtn').addEventListener('click',shareProfile);document.querySelector('#shareXBtn')?.addEventListener('click',shareOnX);window.ethereum?.on?.('accountsChanged',accounts=>accounts[0]&&loadProfile(accounts[0],true));window.ethereum?.on?.('chainChanged',chainId=>chainId.toLowerCase()===ABSTRACT.chainId&&activeAddress&&loadProfile(activeAddress,true));
document.querySelector('#loadPublicBtn')?.addEventListener('click',()=>{const address=document.querySelector('#publicAddressInput')?.value.trim();if(/^0x[a-fA-F0-9]{40}$/.test(address))loadProfile(address);else{setStatus('Enter a valid 42-character wallet address.','error');showToast('Invalid wallet address')}});
if(!window.ethereum)document.querySelector('#walletFallback')?.classList.add('visible');
const addressFromUrl=new URLSearchParams(window.location.search).get('address');if(addressFromUrl&&/^0x[a-fA-F0-9]{40}$/.test(addressFromUrl))loadProfile(addressFromUrl);
