import fs from 'node:fs/promises';
import path from 'node:path';
import readline from 'node:readline';
import { createPublicClient, createWalletClient, http, parseAbi, publicActions } from 'viem';
import { privateKeyToAccount } from 'viem/accounts';
import { abstract } from 'viem/chains';
import { PROOFLY_ABI, PROOFLY_BYTECODE } from '../src/generated/prooflyRegistry.js';

const RPC_URL = 'https://api.mainnet.abs.xyz';

function ask(question, secret = false) {
  return new Promise(resolve => {
    const input = process.stdin;
    const output = process.stdout;
    output.write(question);
    if (!secret || !input.isTTY) {
      const rl = readline.createInterface({ input, output, terminal: false });
      rl.once('line', answer => { rl.close(); resolve(answer.trim()); });
      return;
    }
    let answer = '';
    const onData = chunk => {
      const char = chunk.toString();
      if (char === '\u0003') { input.setRawMode(false); input.pause(); process.exit(1); }
      if (char === '\r' || char === '\n') { input.setRawMode(false); input.removeListener('data', onData); output.write('\n'); resolve(answer.trim()); return; }
      if (char === '\u007f') { answer = answer.slice(0, -1); return; }
      answer += char;
    };
    input.setRawMode(true); input.resume(); input.on('data', onData);
  });
}

async function waitFor(publicClient, hash, label) {
  console.log(`${label}: ${hash}`);
  const receipt = await publicClient.waitForTransactionReceipt({ hash });
  if (receipt.status !== 'success') throw new Error(`${label} failed`);
  return receipt;
}

const rawKey = await ask('Abstract mainnet private key (hidden, never saved): ', true);
const privateKey = rawKey.startsWith('0x') ? rawKey : `0x${rawKey}`;
if (!/^0x[0-9a-fA-F]{64}$/.test(privateKey)) throw new Error('Invalid private key format');

const account = privateKeyToAccount(privateKey);
const publicClient = createPublicClient({ chain: abstract, transport: http(RPC_URL) });
const walletClient = createWalletClient({ account, chain: abstract, transport: http(RPC_URL) }).extend(publicActions);
const balance = await publicClient.getBalance({ address: account.address });
console.log(`\nDeploying from: ${account.address}`);
console.log(`Balance: ${(Number(balance) / 1e18).toFixed(6)} ETH`);
console.log('Network: Abstract mainnet (chain 2741)');
const confirm = await ask('Type DEPLOY to deploy and create starter transactions: ');
if (confirm !== 'DEPLOY') { console.log('Cancelled.'); process.exit(0); }

const txs = {};
const deployHash = await walletClient.sendTransaction({ account, data: PROOFLY_BYTECODE });
txs.registryDeployment = deployHash;
const deployReceipt = await waitFor(publicClient, deployHash, 'Registry deployment');
const registry = deployReceipt.contractAddress;
if (!registry) throw new Error('No contract address returned');
console.log(`Registry: ${registry}`);

const send = async (functionName, args, label) => {
  const hash = await walletClient.writeContract({ address: registry, abi: PROOFLY_ABI, functionName, args });
  txs[label] = hash;
  return waitFor(publicClient, hash, label);
};

await send('mintPassport', [], 'Passport mint');
for (const [name, uri] of [
  ['Genesis Explorer', 'ipfs://proofly/genesis-explorer'],
  ['Abstract Native', 'ipfs://proofly/abstract-native'],
  ['First Signal', 'ipfs://proofly/first-signal'],
  ['Community Builder', 'ipfs://proofly/community-builder']
]) await send('createBadge', [name, uri], `Badge: ${name}`);
for (const [name, badgeId] of [
  ['Explore an Abstract app', 1n],
  ['Claim your first proof', 2n],
  ['Support the community', 4n]
]) await send('createQuest', [name, badgeId], `Quest: ${name}`);
await send('createBattle', ['Season 01 · Explorer race', 604800n], 'Season battle');

const deployedPath = path.resolve('src/deployed.js');
await fs.writeFile(deployedPath, `// Generated by deploy-mainnet.mjs\nexport const DEPLOYED_REGISTRY_ADDRESS = '${registry}';\n`);
await fs.writeFile(path.resolve('deployed-address.json'), JSON.stringify({ network: 'abstract-mainnet', chainId: 2741, registry, deployer: account.address, transactions: txs }, null, 2));
console.log(`\nDone. Registry saved to ${deployedPath}`);
console.log(`Explorer: https://abscan.org/address/${registry}`);
console.log('The private key was only held in memory and was not written to disk.');
