// Generated by deploy-mainnet.mjs
export const DEPLOYED_REGISTRY_ADDRESS = '0xab9e02e861bc0948ba5f9e6cd6bb398ade07b00a';
export const DEPLOYMENT = {
  network: 'Abstract mainnet',
  chainId: 2741,
  deployer: '0x304779882E31A4C98C9042Bbde1d3C59Cc0b1221',
  registry: DEPLOYED_REGISTRY_ADDRESS,
  explorer: `https://abscan.org/address/${DEPLOYED_REGISTRY_ADDRESS}`,
  starterBadges: {
    genesisExplorer: { id: 1, name: 'Genesis Explorer' },
    abstractNative: { id: 2, name: 'Abstract Native' },
    firstSignal: { id: 3, name: 'First Signal' },
    communityBuilder: { id: 4, name: 'Community Builder' }
  },
  starterQuests: {
    exploreAbstractApp: { id: 1, rewardBadgeId: 1 },
    claimFirstProof: { id: 2, rewardBadgeId: 2 },
    supportCommunity: { id: 3, rewardBadgeId: 4 }
  },
  starterBattle: { id: 1, name: 'Season 01 · Explorer race' }
};
